# helm install stable/jenkins --name jenkins --namespace jenkins --values helm/jenkins-values --set master.hostName=...
  master:
    # imageTag: "2.190.1-alpine"  
    imageTag:: "2.204.1alpine"
    cpu: "500m"
    memory: "500Mi"
    serviceType: ClusterIP
    # serviceAnnotations:
    #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    installPlugins:
    - durable-task:1.28
    - workflow-durable-task-step:2.28
    - blueocean:1.10.1
    - credentials:2.3.0
    - ec2:1.39
    - git:3.9.1
    - git-client:2.7.6
    - github:1.29.3
    - kubernetes:1.23.1
    - pipeline-utility-steps:2.2.0
    - pipeline-model-definition:1.3.4.1
    - slack:2.14
    - thinBackup:1.9
    - workflow-aggregator:2.6
    - ssh-slaves:1.29.4
    - ssh-agent:1.17
    - jdk-tool:1.2
    - command-launcher:1.3
    - github-oauth:0.31
    - google-compute-engine:1.0.8
    - pegdown-formatter:1.3
    - credentials-binding:1.17
    - docker-commons:1.15
    ingress:
      ApiVersion: extensions/v1beta1
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        nginx.ingress.kubernetes.io/proxy-body-size: 50m
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        ingress.kubernetes.io/proxy-body-size: 50m
        ingress.kubernetes.io/proxy-request-buffering: "off"
      tls:
        - secretName: psamman-com-nginx-ingress
          hosts:
            - jenkins.psamman.com
    hostName: jenkins.psamman.com
    customConfigMap: false
    credentialsXmlSecret: 
    secretsFilesSecret: 
    DockerVM: false
    # DockerAMI: 
    # GProject:
    # GAuthFile:
    # GlobalLibraries: true
  rbac.create:
    install: true
    serviceAccountName: default
  # Role reference
    roleRef: cluster-admin
    roleBindingKind: ClusterRoleBinding
 